### ISSUE TITLE
Bugged Trainer NPCs

### ISSUE THREAD

**Issue by Cencor126** [ObliqueNET/Terra#30]
As mentioned in the title, I found a few NPCs that didn't allow for any battle at all, despite giving the message "This trainer can only be battled once per Minecraft day". Listed co-ordinates are the (x,z) values. 

(121,-432)
(2,-957)
(259,-840)
(21,192)
(577,-534) Boss NPC "Rare"
(190,400)
(764,688)
(614,615)
(658,659)
(990,402)
(1002,310)
(924,233)
(659,-3)
(683,-234)
(-174,517)

(-119, 462) Boss NPC "Uncommon"
Not quite sure if this is meant to happen, but this NPC only allows for one battle per player lifetime. The other Boss NPCs use the same cooldown as normal trainer NPCs.

**Comment by Kitsune30** [comment]
I have fixed everything but the following:
(577, -534) Seems to be working as intended
(764, 688)
(683, -234)

**Comment by Cencor126** [comment]
(764, 688) appears to be working now, but (577, -534) and (683, -234) still cannot be engaged. NPC message is still the same.

**Comment by Kitsune30** [comment]
Fixed those.
